services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tickhawk
      - JWT_SECRET=your_jwt_secret
      - S3_PROVIDER=local
      - PORT=3000
      - LOCAL_UPLOAD_PATH=/app/uploads
      - LOG_LEVEL=info
      - ENABLE_SWAGGER=true
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mongodb
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
  uploads_data: